name: 'Tenderly Virtual TestNet Setup'
description: 'Sets up a Tenderly Virtual TestNet and exposes RPC link as an environment variable'
inputs:
  mode:
    description: 'Operation mode (CI or CD). CD mode will persist the TestNet and track deployments'
    required: false
    default: 'CI'
  access_key:
    description: 'Tenderly API Access Key'
    required: true
  project_name:
    description: 'Tenderly Project Name'
    required: true
  account_name:
    description: 'Tenderly Account Name'
    required: true
  testnet_name:
    description: 'Display name for the Virtual TestNet'
    required: true
    default: 'CI Virtual TestNet'
  network_id:
    description: 'Network ID to fork (e.g., 1 for Ethereum mainnet, 137 for Polygon)'
    required: true
    default: '1'
  chain_id:
    description: 'Chain ID for Virtual TestNet'
    required: false
  block_number:
    description: 'Block number to fork from (in hex or "latest")'
    required: true
    default: 'latest'
  state_sync:
    description: 'State Sync enables you to access the latest values of storage slots and account balances'
    required: false
    default: 'false'
  public_explorer:
    description: 'Public explorer option generates a public URL that you can share with anyone and allow them to view transactional activity on your TestNet'
    required: false
    default: 'false'
  verification_visibility:
    description: 'If Public Explorer is enabled, level of visibility for smart contracts deployed on your TestNet'
    required: false
    default: 'bytecode'

runs:
  using: 'node20'
  main: './dist/index.js'
  post: './dist/cleanup.js'
  post-if: always()

branding:
  icon: 'cloud'
  color: 'white'