[profile.default]
src = "src"
out = "out"
libs = ["lib"]
cbor_metadata = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[etherscan]
## placeholders must be replaced with key ("string"), chain_id (number), and tenderly_foundry_verification_url ("string")
unknown_chain = { key = "P2cyIs74Ml0YuA-7jTx4AguYIxcWCoRq", chain = 7357137, url = "https://virtual.mainnet.rpc.tenderly.co/e185777c-a521-4078-8c82-17c04b31c96d/verify/etherscan" }