[profile.default]
src = "src"
out = "out"
libs = ["lib"]
cbor_metadata = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[etherscan]
## placeholders must be replaced with API key ("string"), chain_id (number), and tenderly_foundry_verification_url ("string")
unknown_chain = { key = "O1Us9aUirXqCfHf81hS8MD7-0McDd4EX", chain = 73578453, url = "https://virtual.mainnet.rpc.tenderly.co/836a546d-9ead-4e5c-9ec5-5d998e11dd96/verify/etherscan" }
